name: busecke_etal_grl_2019_omz_euc
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  #
  - astropy
  - xarray
  - xgcm
  - jupyter
  - dask
  - distributed
  - numpy
  - scipy
  - matplotlib
  - cartopy
  - palettable
  - gsw
  - nc-time-axis
  - pip:
    - "--editable=git+https://github.com/jbusecke/xarrayutils.git@master#egg=xarrayutils"
